### ISSUE TITLE
Replace ifconfig.me/ip call with something that is more stable

### ISSUE THREAD

**Issue by ryandanthony** [OctopusDeploy/OctopusDSC#10]
I am seeing frequent failures where Get-MyPublicIPAddress won't return an IP address, and therefore won't allow the machine to register properly with the Octopus Server. 

I propose that Get-MyPublicIPAddress should use checkip.dyndns.com instead of ifconfig.me

``` powershell
$ip = $downloader.DownloadString("http://checkip.dyndns.com") -replace '[^\d\.]'
```

To troubleshoot the issues I was seeing after frequent failed registrations for machines I am deploying in Azure, I wrote this quick test to see if I would get any errors. 

``` powershell
for($i=1; $i -le 10; $i++)
{
    Write-Host "Getting public IP address" 

    $downloader = new-object System.Net.WebClient 
    $ip = ""
    try
    {
        $ip = $downloader.DownloadString("http://ifconfig.me/ip") 
    }
    catch [system.exception]
    {
        $errorMessage = $_.Exception.Message
        Write-Host "Error: $errorMessage"
    }
    finally
    {
        Write-Host $ip  
        $downloader.Dispose();
    }
}
```

Every time I ran it, I would get at least one failure (generally more than one): "Unable to connect to the remote server". (your mileage may vary).

**Comment by michaelnoonan** [comment]
Hey @ryandanthony, I've just been investigating an issue for another Customer and it would appear we've run in to the same bug at least once...

```
Getting public IP address
Public IP address:
Configuring and registering Tentacle
Octopus Deploy: Tentacle version 2.6.5.1010
Creating empty configuration file: C:\\Octopus\\Tentacle\\Tentacle.config
Saving instance: Tentacle
Octopus Deploy: Tentacle version 2.6.5.1010
Home directory set to: C:\\Octopus
Octopus Deploy: Tentacle version 2.6.5.1010
Application directory set to: C:\\Applications
Octopus Deploy: Tentacle version 2.6.5.1010
Services listen port: 10933
Octopus Deploy: Tentacle version 2.6.5.1010
A new certificate has been generated and installed. Thumbprint:
02D2CB04DD3AC1D4F8E95B7C06E5417076F09866
Octopus Deploy: Tentacle version 2.6.5.1010
Service installed
Registering with arguments: register-with --instance Tentacle --server http://octoserv1.cloudapp.net --name OCTOTENT1 --publicHostName  --apiKey API-IKNBZVOQPIT5ALWBUN9IDRYBACY --comms-style TentaclePassive --force --console --environment Test --role web-server
Octopus Deploy: Tentacle version 2.6.5.1010
-------------------------------------------------------------------------------
Error: Unrecognized command line arguments: API-IKNBZVOQPIT5ALWBUN9IDRYBACY
-------------------------------------------------------------------------------
Full error details are available in the log files.

```

**Comment by zentron** [comment]
This could also be amended to check if the provided server is on the same subnet and if so just revert to using the internal IP address before escalating and trying a public IP, finally failing with a helpful message if the IP address still cant be resolved.

**Comment by matt-richardson** [comment]
As of https://github.com/OctopusDeploy/OctopusDSC/commit/0f5b8f46158f906cd7115a3dbd2e1381eab5f1cf, you can specify how you want it to determine the public host name: `PublicIP`, `FQDN`, `ComputerName` or `Custom`. This should allow you to specify the hostname you want.

I'm going to close this as resolved.
