### ISSUE TITLE
DATABASE command should retry if a SQL deadlock occurs

### ISSUE THREAD

**Issue by stopthatastronaut** [OctopusDeploy/OctopusDSC#102]
If multiple databases are creating in parallel or near-parallel, a lock on `model` occurs, and OctopusDSC dies.

We can get past this with retries.

**Comment by matt-richardson** [comment]
Is this something that should be fixed at the DSC level, or in Octopus itself?

**Comment by matt-richardson** [comment]
If this is still happening, we should fix in Octopus itself.
