### ISSUE TITLE
cTentacleAgent Policy parameter does not handle spaces in variable names well

### ISSUE THREAD

**Issue by lawrencewilson** [OctopusDeploy/OctopusDSC#105]
Attempting to assign the Policy parameter with a string containing spaces will cause the Tentacle to fail registration.

Affected DSC Resource: cTentacleAgent
OctopusDSC Version: 3.0.169

Related Support Tickets: https://help.octopusdeploy.com/discussions/problems/68066-bug-octopusdsc-extension-fails-when-machine-policy-name-contains-spaces

**Comment by stopthatastronaut** [comment]
This is fixed, but the issue wasn't closed. We test against a policy with a space in the name

https://github.com/OctopusDeploy/OctopusDSC/blob/a91117fb6da31473e2ae4fa2aba8c904d0926bfa/Tests/Scenarios/Tentacle_Scenario_01_Install.ps1#L47
