### ISSUE TITLE
which keyword issue

### ISSUE THREAD

**Issue by mikejwhat** [OctopusDeploy/OctopusDSC#110]
Not sure whether this is an issue or not - I can't work out where the 'which' command is supposed to come from? I keep getting the below error when trying to run build-hyperv.ps1. I've resorted to commenting the prerequisite checks for now.

------------------------------------------------------------------------------------------------------------------

& : The term 'which' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that the
path is correct and try again.
At C:\Users\mike\Downloads\OctopusDSC-master\Tests\powershell-helpers.ps1:32 char:5
+   & which $appName | Out-Null
+     ~~~~~
    + CategoryInfo          : ObjectNotFound: (which:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by matt-richardson** [comment]
The hyperv build is still a bit of a work in progress, but it should work.

That said, `which` is a linux command, not a windows command. It should be doing some OS detection and using `where` on windows.

I need to check with @stopthatastronaut to see what the status is with this part. 

Out of curiosity, are you using PSCore or normal PowerShell?

**Comment by mikejwhat** [comment]
Hi matt. I'm using normal PowerShell (5.1).

**Comment by stopthatastronaut** [comment]
Hey guys,

The hyper-v bit is indeed still a work in progress. TBH I'm surprised anyone's tried to run it other than me. 

`which` is a linux command as Matt mentioned, but it's installable on Windows.

In this instance it can probably be replaced with (or aliased to) `Get-Command`

**Comment by matt-richardson** [comment]
Seeing it's in the shared code, if we replaced it, it'd break when the other ones (eg virtualbox) are run under pscore on linux....

I'm thinking something like this logic: “if variable `$iswindows` is not defined or `$iswindows` is `$true` then use `where` otherwise use `which`"

**Comment by matt-richardson** [comment]
@mikejwhat - can you test the change I made in this PR and see if it solves the problem for you?

**Comment by mikejwhat** [comment]
Sure. Will get back to you in a day or two. Thanks.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mikejwhat** [comment]
Thanks for sorting this.
