### ISSUE TITLE
Failure with Azure SQL

### ISSUE THREAD

**Issue by andylbrummer** [OctopusDeploy/OctopusDSC#124]
I'm trying to setup octopus deploy using an Azure SQL database from an azure vm. The issue I'm running into is in the call to octopus.server database with the -grant option. 

It looks like this depends on the sys.server_principals table, which isn't included with Azure SQL: https://docs.microsoft.com/en-us/sql/relational-databases/system-catalog-views/sys-server-principals-transact-sql

I can manually run the command without the grant and it appears to run fine.

**Comment by andylbrummer** [comment]
Never mind, I found the GrantDatabasePermissions=$false option

**Comment by matt-richardson** [comment]
Glad you got it sorted @andylbrummer.
