### ISSUE TITLE
Defining CustomPublicHostName as a parameter does not work

### ISSUE THREAD

**Issue by StevePB61** [OctopusDeploy/OctopusDSC#126]
hi,

I have a PowerShell script which uses a AWS ami to collect the public IP address then uses this to set the CustomPublicHostName. This throws an error. "A parameter cannot be found that matches parameter name 'CustomPublicHostName'."

[String]$machinename = Invoke-RestMethod -Uri http://169.254.169.254/latest/meta-data/public-ipv4

Configuration AppOctConfig
{
    param ($ApiKey, $OctopusServerUrl, $Environments, $machinename)

    Import-DscResource -Module OctopusDSC

    Node "localhost"
    {
        cTentacleAgent OctopusTentacle
        {
            Ensure = "Present"
            State = "Started"

            # Tentacle instance name. Leave it as 'Tentacle' unless you have more
            # than one instance
            Name = "Tentacle"

            OctopusServerUrl = $OctopusServerUrl
            ApiKey = $ApiKey
            Environments = $Environments
            Roles = 'ApplicationServer,DatabaseServer'

            # How Tentacle will communicate with the server
            CommunicationMode = 'Poll'
            ServerPort = '10943'
            PublicHostNameConfiguration = 'Custom'
            CustomPublicHostName = $machinename

            # Where Octopus should store its working files, logs, packages etc
            TentacleHomeDirectory = "C:\Octopus"

            # Where deployed applications will be installed by Octopus
            DefaultApplicationDirectory = "C:\Octopus\Applications"

        }
    }
}

AppOctConfig -ApiKey $ApiKey -OctopusServerUrl $OctopusServerUrl -Environments $Environments -CustomPublicHostName $machinename

**Comment by matt-richardson** [comment]
What version of the DSC resource are you using?
The parameter [is correct](https://github.com/OctopusDeploy/OctopusDSC/blob/master/OctopusDSC/DSCResources/cTentacleAgent/cTentacleAgent.psm1#L35), so I suspect that you've got an old version of the DSC resource.

Also, can you share the full log?

**Comment by StevePB61** [comment]
Sure Here is the info.
PS C:\Windows\system32> Get-DscResource -Module OctopusDSC

ImplementedAs   Name                      ModuleName                     Version    Properties                                        
-------------   ----                      ----------                     -------    ----------                                        
PowerShell      cOctopusEnvironment       OctopusDSC                     4.0.250    {Ensure, Url, DependsOn, EnvironmentName...}      
PowerShell      cOctopusSeqLogger         OctopusDSC                     4.0.250    {Ensure, InstanceType, DependsOn, Properties...}  
PowerShell      cOctopusServer            OctopusDSC                     4.0.250    {Name, AllowCollectionOfUsageStatistics, AllowU...
PowerShell      cOctopusServerActiveDi... OctopusDSC                     4.0.250    {InstanceName, ActiveDirectoryContainer, AllowF...
PowerShell      cOctopusServerAzureADA... OctopusDSC                     4.0.250    {InstanceName, ClientId, DependsOn, Enabled...}   
PowerShell      cOctopusServerGoogleAp... OctopusDSC                     4.0.250    {InstanceName, ClientID, DependsOn, Enabled...}   
PowerShell      cOctopusServerGuestAut... OctopusDSC                     4.0.250    {InstanceName, DependsOn, Enabled, PsDscRunAsCr...
PowerShell      cOctopusServerOktaAuth... OctopusDSC                     4.0.250    {InstanceName, ClientId, DependsOn, Enabled...}   
PowerShell      cOctopusServerUsername... OctopusDSC                     4.0.250    {InstanceName, DependsOn, Enabled, PsDscRunAsCr...
PowerShell      cOctopusServerWatchdog    OctopusDSC                     4.0.250    {InstanceName, DependsOn, Enabled, Instances...}  
PowerShell      cTentacleAgent            OctopusDSC                     4.0.250    {Name, ApiKey, CommunicationMode, CustomPublicH...
PowerShell      cTentacleWatchdog         OctopusDSC                     4.0.250    {InstanceName, DependsOn, Enabled, Instances...}  

PS C:\Scripts> .\WebOctConfig.ps1
WebOctConfig : A parameter cannot be found that matches parameter name 'CustomPublicHostName'.
At C:\Scripts\WebOctConfig.ps1:39 char:94
+ ... usServerUrl -Environments $Environments -CustomPublicHostName $machin ...
+                                             ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [WebOctConfig], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,WebOctConfig

**Comment by StevePB61** [comment]
Perfect!! Thank you!
