### ISSUE TITLE
Certificate management options for cOctopusServer

### ISSUE THREAD

**Issue by adhodgson1** [OctopusDeploy/OctopusDSC#131]
See this for context:
https://octopusdeploy.uservoice.com/forums/170787-general/suggestions/11254536-support-multiple-ssl-bindings-to-octopus-server-us

I believe that given the case where you have one certificate in the personal store with the same name as your web prefix, this will work out of the box.

In our case it fails because we have a wildcard cert and it will never match, so I have to set up a manual script task to set the certificate based on the app as discussed in the article above.

Could this be added as a parameter to the DSC somehow?

**Comment by matt-richardson** [comment]
At the moment, the OctopusDSC module doesn't have any knowledge of the `netsh` changes needed to configure the http listener. Regardless of whether we use a wildcard cert or a specific cert, the `netsh` call still needs to be made.

While it might be a good idea for the `OctopusDSC` module to support the SSL configuration, given it is [relatively easy](https://powershell.org/forums/topic/port-configuration-with-dsc/#post-62691) to implement, its unlikely that this will reach the top of our todo list.

That said, we'd happily accept a PR for it. Closing for now, but feel free to reach out if you're interested in submitting a PR.
