### ISSUE TITLE
Octopus Server master key emitted into logs

### ISSUE THREAD

**Issue by thekatstevens** [OctopusDeploy/OctopusDSC#132]
It was reported that OctopusDSC is emitting the server master key into the output logs when running the database command:

```
2018-05-22 10:34:04.7785 3492 1 INFO CommandLine: C:\Program Files\Octopus Deploy\Octopus\Octopus.Server.exe database --instance OctopusServer --connectionstring Data Source=[…]; Initial Catalog=Octopus; Integrated Security=SSPI;Max Pool Size=200 --masterKey […]
```

Generally speaking, whomever is running the DSC should have equal access to retrieve the master key from the CLI so there isn't a vulnerability here, but we shouldn't be outputting the master key in plaintext form if it can be avoided.

**Comment by adhodgson1** [comment]
I was the original reporter of this issue. I didn't believe it was an issue with octopusDSC as I believed the logs were being created by the Octopus process itself when the command line was being run.

**Comment by thekatstevens** [comment]
@adhodgson1 My understanding is that the Octopus DSC is generating that command to configure the database with the supplied master key, and the command line is being emitted into the logs in plaintext - usually you would run this command directly at a command prompt, and you would supply the master key. If this is the case, then we need to mask the masterkey when the line gets outputted.

@stopthatastronaut have I got that right?

**Comment by adhodgson1** [comment]
The logs I am talking about here are the actual Octopus server logs in the Logs directory.  I don't believe the DSC module writes to those does it?

What I believed was happening was that the DSC was running the Octopus configuration command and the configuration command was logging the command out to the server log file.  Sorry if I have got the wrong end of the stick.

**Comment by thekatstevens** [comment]
Ahh you're probably right, I'm not an expert at the command-line aspect of Octopus so I think I misunderstood. 

I'll follow it up more tomorrow and see what logging changes we might need to make inside Octopus to mask the master key. Thanks for follow up here!

**Comment by stopthatastronaut** [comment]
Ah, that's some interesting info. There might be master keys being emitted in two places. My change above supresses it in OctopusDSC verbose output. As Andrew has noted, we'll look at it in the Octopus logs too.

**Comment by adhodgson1** [comment]
Good point, I didn't think about verbose output.  I am not using verbose output, so the master key I believe I was seeing is a result of the log from the Octopus command line tool.

**Comment by stopthatastronaut** [comment]
OK, the verbose output is suppressed, so I'll close this ticket - @thekatstevens, can we make sure we've got an issue tracked for the Octopus Server logs s that doesn't slip? Cheers guys.
