### ISSUE TITLE
Getting the following error when OctopusMasterKey is supplied 

### ISSUE THREAD

**Issue by Sammmmm** [OctopusDeploy/OctopusDSC#139]
PowerShell DSC resource cOctopusServer  failed to execute Test-TargetResource functionality with error message:
Parameter 'OctopusAdminCredential' must be supplied when 'Ensure' is 'Present' and you have not supplied a master key
to use an existing database.

I have supplied a master key

**Comment by cvandal** [comment]
Hi @Sammmmm, can you please provide a code snippet of your `cOctopusServer` block?

**Comment by Sammmmm** [comment]
cOctopusServer OctopusServer
        {
            Ensure = "Present"
            State = "Started"

            # Server instance name. Leave it as 'OctopusServer' unless you have more than one instance
            Name = "OctopusServer"

            # The url that Octopus will listen on
            WebListenPrefix = "http://localhost:80"

            SqlDbConnectionString = 'Server=foobar.rds.amazonaws.com;Database=bar;User Id=foo;Password=baz;'

            HomeDirectory = "C:\Octopus"

            LicenseKey = $license
            OctopusMasterKey = $masterkey # octopus master key
            # OctopusAdminCredential = $servicecreds 
            OctopusServiceCredential = $servicecreds 
            
            # OctopusBuiltInWorkerCredential

            AllowUpgradeCheck = $true
            AllowCollectionOfUsageStatistics = $false
            ForceSSL = $true
            LogTaskMetrics = $false
            LogRequestMetrics = $false
            ListenPort = 10943

        }

**Comment by cvandal** [comment]
@Sammmmm thanks for sending that through. Looks like you have your `OctopusAdminCredential` commented out. Can you please remove the `#` and try again?

**Comment by Sammmmm** [comment]
That's the problem though, the error indicates i need either an OctopusMasterKey or an OctopusAdminCredential, the former I have specified and am using an existing database.  If the latter is also required, the error message I get is incorrect.

**Comment by Sammmmm** [comment]
I'm probably constructing masterkey incorrectly, I'm constructing it as a PSCredential with the key the user and password.  However, if I do include a bogus OctopusAdminCredential, the master key is accepted and works correctly (whereas when I use the wrong master key it throws errors about being unable to decrypt parts of the database).

**Comment by cvandal** [comment]
That's interesting. Try constructing it like this and letting me know how you go:

```
$octopusMasterKey = "xxx"
$octopusMasterKey = New-Object System.Management.Automation.PSCredential ("NA", (ConvertTo-SecureString $octopusMasterKey -AsPlainText -Force))
```

**Comment by adhodgson1** [comment]
I've just upgraded OctopusDSC to try out this functionality as I didn't want to specify an admin account and am hitting the same issue.  if I provide just a master key I am being told that the master key is not provided and so I must use admin credentials.

I am getting the master key from an automation account credential object:

$MasterKeyCredential = Get-AutomationPSCredential -Name "OctopusMasterKey"
    cOctopusServer "Octopus" {
[...]
      OctopusMasterKey = $MasterKeyCredential
}

I know I am getting the master key as I am building new servers each time and can see the master key in the logs of the Octopus command output.

Thanks.
Andrew.

**Comment by cvandal** [comment]
Hi @Sammmmm and @adhodgson1. I've located the bug in our code, fixed it, and tested it locally. There's now have a PR with my changes that's currently building and waiting on approval so once that's sorted I will merge it into the master branch. Thank you gents for raising this :+1:

**Comment by cvandal** [comment]
Fix has been pushed to the master branch.
