### ISSUE TITLE
Artifacts, Packages and TaskLogs directories overridden by DSC

### ISSUE THREAD

**Issue by adhodgson1** [OctopusDeploy/OctopusDSC#141]
Hi,

I have the following DSC which is used to rebuild Octopus in a HA setup which is already configured:

    cOctopusServer "Octopus" {
      HomeDirectory = "E:\Octopus"
    [...]
    }

What I expected this to do was to set the home directory on the server to E:\Octopus, but leave the other directories alone.  What it actually does is set the directories to E:\Octopus\folder, overriding the value presently configured in the database.  I believe that is because the DSC is setting the parameters to default values rather than checking the existing value.

**Comment by matt-richardson** [comment]
The DSC assumes its in control of all the properties - if you're using the DSC, you should make that the master source of truth. If the Artifacts/Packages/TaskLogs paths need to be set to a different location, you need to add them to your DSC configuration.

Technically, it would be possible to treat null as "use whatever is in the database, or default to under the home directory if its a new instance", but that goes against the idea of designing your Desired State, and having a single source of truth.

Hope that helps!
