### ISSUE TITLE
cTentacleAgent: Issue while configuring Octopus Tentacle

### ISSUE THREAD

**Issue by ssijbabu** [OctopusDeploy/OctopusDSC#150]
While running the below configuration, Octopus Tentacle is installing fine but getting error during the configuration. 

P.S My PC is behind the proxy server. 

Please find my configuration below.
```
cTentacleAgent OctopusTentacle
{
    Ensure = "Present"
    State = "Started"

    Name = "Tentacle"

    DisplayName = "Octopus Tentacle"

    # Required parameters. See full properties list below
    ApiKey = 'API-xxxxxxxxxxxxxxxxxxxxxxxx'
    OctopusServerUrl = 'https://xxxxxxxx.xxxxxx.com'
    Environments = @('xxxx_DEV')
    Roles = @('xxxx_App_Server','xxxx_web_Server')
    TentacleDownloadUrl64 = '\\xxxx123\software\Octopus.Tentacle.3.21.0-x64.msi'
    TentacleDownloadUrl = '\\xxxx123\software\Octopus.Tentacle.3.21.0.msi'
}
```

This is the error i am getting during the configuration.
Error:

```
VERBOSE: [xxxxx]: [[cTentacleAgent]OctopusTentacle] GET https://api.ipify.org/ with 0-byte payload
VERBOSE: [xxxxx]: [[cTentacleAgent]OctopusTentacle] Unable to connect to the remote server
You cannot call a method on a null-valued expression.
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : InvokeMethodOnNull
    + PSComputerName        : localhost
 
VERBOSE: [xxxxx]: [[cTentacleAgent]OctopusTentacle] Public host name:
VERBOSE: [xxxxx]: [[cTentacleAgent]OctopusTentacle] Registering with arguments: register-with --instance Tentacle --server https://xxxxxxxx.xxxxxx.com --nam
e Octopus Tentacle --apiKey API-xxxxxxxxxxxxxxxxxxxxxxxx --force --console --comms-style TentaclePassive --publicHostName  --environment xxxx_DEV --role xxxx_App_Server --role xxxx_web_Server
Unrecognized command line arguments: xxxx_DEV
    + CategoryInfo          : NotSpecified: (Unrecognized co...uments: xxxx_DEV:) [], CimException
    + FullyQualifiedErrorId : NativeCommandError
    + PSComputerName        : localhost
```

**Comment by matt-richardson** [comment]
Thanks for reporting @ssijbabu.

I've got a feeling its got something to do with the name of your `xxxx_DEV` environment. Any chance you can share the full name?

If you're not comfortable sharing in public, feel free to ping over the logs to support@octopus.com and I'll take a look there.

**Comment by matt-richardson** [comment]
Ahh, great to hear you've solved it. I'm not sure there's any reasonable default to this value, as it will be different for everyone. Changing the default could break other people who have not specified the value.

I suspect the best answer is to fail if we cant determine the public ip, rather than trying to continue.

**Comment by ssijbabu** [comment]
I understand. Still we need to fix the above issue. If you see the first error (line 2 of the error message), it is unable to get the public IP address. so while trying to register the tentacle with the server, the command line is intepreting **--environment** as a value to the **--PublicHostName** options and **xxxx_Dev** as commandline option.

**Comment by stopthatastronaut** [comment]
So if I understand it, the original issue was a failure to connect to https://api.ipify.org/, which was bypassed by manually setting the PublicHostName variable. 

I think we could have a fallback option for that operation, and maybe a more informative error message along with the failure.

**Comment by stopthatastronaut** [comment]
Resolved by adding a more informative error and two fallback services
