### ISSUE TITLE
Virtualbox tests fail if Hyper-V is installed but not in use

### ISSUE THREAD

**Issue by devbeard** [OctopusDeploy/OctopusDSC#176]
Later versions of Windows 10 allows Virtualbox to be the primary hypervisor, whilst Hyper-V feature is still installed. 

If you run `vagrant up --provider virtualbox` it seems like the linked if block is still evaluated as it fails with error message referencing "External Connection". If the Hyper-V block is commented out, the error does not occur.

https://github.com/OctopusDeploy/OctopusDSC/blob/6b30ffa3b75013cfba4cf2f1b1e3da0d8f5905f5/vagrantfile#L78-L87

**Reproduce:**

- Windows 10, version 1709 or later
- Hyper-V enabled and installed
- Disable Hyper-V with `bcdedit /set hypervisorlaunchtype off`
- Install Virtualbox and reboot
- Execute `.\build-virtualbox.ps1`
- Exceptions are thrown for unknown bridge "External Connection", which only is mentioned in the Hyper-V code block on line 81: https://github.com/OctopusDeploy/OctopusDSC/blob/6b30ffa3b75013cfba4cf2f1b1e3da0d8f5905f5/vagrantfile#L81

**Comment by stopthatastronaut** [comment]
There's a PR in-progress to switch Hyper-V to the default switch, which _might_ alter this behaviour, since that line will now default to 'Default Switch', which should be present on most recent installs of Hyper-V.

**Comment by matt-richardson** [comment]
We're pretty sure this is resolved now. If you're still facing it, please let us know.
