### ISSUE TITLE
Consider updating to new networking in Hyper-V

### ISSUE THREAD

**Issue by devbeard** [OctopusDeploy/OctopusDSC#177]
**Observation:**
For Hyper-V, the test script checks for a network bridge named "External Connection" and fails if this does not exist. With newer versions of Windows (1709 "Creators Update" and higher), the default networking behavior of Hyper-V is changed to prefer a "Default" adapter with NAT. As this networking adapter already exists when enabling Hyper-V, creating an additional adapter can cause extreme degradation of networking performance.

https://mikefrobbins.com/2018/11/08/managing-the-hyper-v-default-switch-in-windows-10-version-1709-and-higher-with-powershell/

**Suggestion:**
Transition to use the default adapter in the powershell scripts and vagrant file, or if backwards compatibility is needed, make the switch name an environment variable and extend the test that checks for the switch.

https://github.com/OctopusDeploy/OctopusDSC/blob/6b30ffa3b75013cfba4cf2f1b1e3da0d8f5905f5/build-hyperv.ps1#L66-L70

**Comment by devbeard** [comment]
https://github.com/OctopusDeploy/OctopusDSC/blob/master/build-hyperv.ps1#L66-L70

**Comment by stopthatastronaut** [comment]
Hey @devbeard 

I hopped onto a new branch and made some changes to use the default switch. Seemed to work OK, though you do still have to specify 'Default Switch' in the vagrantfile, or it'll prompt for a choice for a system with multiple adapters like mine.

I had expected I'd need to configure a NAT and DHCP, but it worked just dandy.

I like the suggestion of making it an environment var, with ability to default onto 'Default Switch", so I think that's what I'll go with.

**Comment by stopthatastronaut** [comment]
Shipped this change last night.

**Comment by twerthi** [comment]
The Default Switch can no longer be edited with the latest Windows Update.  Setting the environment variable $env:OctopusDSCVMSwitch works great!
