### ISSUE TITLE
Is this project abandoned ?

### ISSUE THREAD

**Issue by thu2004** [OctopusDeploy/OctopusDSC#18]
Hi

There are some Pull pending requests but no actions or comments. Is this project abandoned ?

Best regards

/Chi Thu Le

**Comment by icebrian** [comment]
+1

Would very much like feedback on matter.

**Comment by SNikalaichyk** [comment]
+1 Up.

**Comment by ITGuyOU** [comment]
@thu2004 , @icebrian, @SNikalaichyk , 
Just created a pull request to fix some issues I found, and that you all were likely to have noticed. Cleaned up quite a bit of the code as well. It looks like I'm the only one active on the project since May.

**Comment by matt-richardson** [comment]
Sorry all, we've appear to have dropped the ball a bit here. We are all heads down busy at the moment, getting ready to get the next release out the door, but as soon as I can get to it, I'll jump on these PRs and issues.

**Comment by hansmelin** [comment]
Thanks for this information! Then I'll just wait!
