### ISSUE TITLE
Tentacle Scenario 3 was moved to a more recent tentacle version in pull #178 

### ISSUE THREAD

**Issue by stopthatastronaut** [OctopusDeploy/OctopusDSC#181]
Tentacle Scenario 3 needs to be a "previous" version in order to test upgrade in Scenario 4, however we run into a `Octopus.Client.Exceptions.OctopusMethodNotAllowedFoundException` when registering 3.2.24 to a spaces-enabled 2019.2.2 server. The  version was shifted in order to build a new version.

We still need to test older version upgrades in this repo.

**Comment by matt-richardson** [comment]
It now uses `3.20`. That's old enough for me.
