### ISSUE TITLE
Would consider adding support for a polling agent in addition to the listening agent?

### ISSUE THREAD

**Issue by erichexter** [OctopusDeploy/OctopusDSC#19]
in our environment we are using polling agents so we dont have to create a bunch of NAT routing rules to each machine in azure.  Would you consider adding this to the existing dsc resource.?  would you take a pull request for it?

**Comment by matt-richardson** [comment]
@erichexter - I've just pushed some changes to https://github.com/ASOS/DevOpsGuysDSC from our internal repo that add support for polling tentacles. Hope this helps!

**Comment by matt-richardson** [comment]
Hi @erichexter - apologies for taking so long to get back to you on this with a real answer.

A few months after my comment above, I joined Octopus 😄 and I've now started looking at bringing the DSC up to date.

I've just pushed a change that adds support for polling tentacles - hope that helps!

**Comment by erichexter** [comment]
Thanks for the follow up. Congrats on join OD. That awesome!.   I have a
custom DSC now, but I would prefer to use the official package.

Eric Hexter

blog | http://Hex.LosTechies.com
info | http://www.linkedin.com/in/erichexter
