### ISSUE TITLE
Add support for TenantedDeploymentParticipation parameter

### ISSUE THREAD

**Issue by tomerMP** [OctopusDeploy/OctopusDSC#190]
Hi,
https://github.com/OctopusDeploy/Issues/issues/3782 has been released for a while now.
It adds support for setting a deployment target as both tenanted and untenanted via API

It would be great if this could be supported here to allow full configuration in a single place

**Comment by stopthatastronaut** [comment]
This change is now merged and will be available in the next version

**Comment by tomerMP** [comment]
Awesome guys. Thanks a ton!!
