### ISSUE TITLE
Support tentacle upgrades

### ISSUE THREAD

**Issue by yannisgu** [OctopusDeploy/OctopusDSC#2]
Would be cool if there would be a parameter where you specify the exact version to install. The module should then also handle updates, when the installed version is lower than the specified version.

**Comment by matt-richardson** [comment]
Hi @yannisgu, really sorry that it has taken us over 2 years to get back to you on this.

You'll be happy to hear that as of commit 441e81bac0c873ae3039f315d66bd9c30e489487, this resource now supports upgrades and even downgrades.

Basically, it remembers what url you requested the initial install from, and if you ever change the configured url, it will download and run the new msi. This means, that you don't get auto upgrades whenever we release a new Tentacle version, but that's probably not the behaviour you want anyway, as you'll most likely be triggering an upgrade from the server.

Hope that helps, and once again, my apologies for taking so long to get back to you.

**Comment by yannisgu** [comment]
Thanks @matt-richardson
