### ISSUE TITLE
cTentacleAgent - .\tentacle.exe not recognised as name of...

### ISSUE THREAD

**Issue by tomerMP** [OctopusDeploy/OctopusDSC#202]
Hi, 
I have been attempting to use this awesome mdule and have hit multiple errors, the first of which begin with the below errors.
I have also attached the event log mentioned.
Anything I am doing wrong? 

[Output.txt](https://github.com/OctopusDeploy/OctopusDSC/files/3134634/Output.txt)

Also had a look at some of the code inside cTentacleAgent.psm1 and found 2 lines that look a little off:

955    : `Invoke-AndAssert {&.\tentacle.exe ($argumentList)}`
1041  : `Invoke-AndAssert { &.\tentacle.exe ($argumentList)}`

I am thinking maybe the lack of white space between '&' and '.\' might be the issue, but have not been able to delve further in just yet

[OctopusDSC.zip](https://github.com/OctopusDeploy/OctopusDSC/files/3134631/OctopusDSC.zip)

**Comment by stopthatastronaut** [comment]
HI @tomerMP 

The space shouldn't be an issue - I suspect maybe the resource has hopped onto the wrong active path somehow.

I'll look into it and see what I can see - we might want to add a more explicit path in the code there, to stop this happening

Jason
