### ISSUE TITLE
Compliance check does not ensure firewall rule

### ISSUE THREAD

**Issue by lonevvolf** [OctopusDeploy/OctopusDSC#205]
If the firewall rule for the Tentacle is not created successfully (or is somehow deleted), this is not detected as drift by the DSC script.

**Comment by matt-richardson** [comment]
Thanks for raising an issue, @lonevvolf.

This is a [known constraint](https://github.com/OctopusDeploy/OctopusDSC/blob/master/README-cTentacleAgent.md#drift) of the current implementation.

We'd like to fix this, but its not near the top of our priority list, unfortunately. We definitely do appreciate PRs though.
