### ISSUE TITLE
Creation of missing environment via cTentacleAgent

### ISSUE THREAD

**Issue by tomerMP** [OctopusDeploy/OctopusDSC#206]
Hi,

This is more of a question/feature request.
I was wondering if cTentacleAgent will create the environments configured if the environment does not yet exist on Octopus server.

The use case is simple, to use OctopusDSC to install agent, create the environment if it does not yet exist, and then create and add the deploy target to the newly created environment, without having to add another node block to configure cOctopusEnvironment

**Comment by matt-richardson** [comment]
`cTentacleAgent` wont create the environment automatically - it assumes it already exists.
That said, [cOctopusEnvironment](https://github.com/OctopusDeploy/OctopusDSC/tree/master/OctopusDSC/DSCResources/cOctopusEnvironment) (which unfortunately is missing a readme) will do that for you.

hope that helps!
