### ISSUE TITLE
cTentacleAgent failed to execute Set-TargetResource

### ISSUE THREAD

**Issue by Andrew-Archon** [OctopusDeploy/OctopusDSC#220]
I'm trying to deploy a VM Scale Set on Azure that uses the Octopus DSC extension.  There are 4 VM instances in the scale set.  The first two instances deploy correctly, however the last two instances are failing with the following error:

`{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.","details":[{"code":"Conflict","message":"{\r\n \"status\": \"Failed\",\r\n \"error\": {\r\n \"code\": \"ResourceDeploymentFailure\",\r\n \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n \"details\": [\r\n {\r\n \"code\": \"VMExtensionProvisioningError\",\r\n \"message\": \"VM has reported a failure when processing extension 'dscExtension'. Error message: \\\"DSC Configuration 'OctopusTentacle' completed with error(s). Following are the first few: PowerShell DSC resource cTentacleAgent failed to execute Set-TargetResource functionality with error message: Command returned exit code 255 The SendConfigurationApply function did not succeed.\\\".\"\r\n }\r\n ]\r\n }\r\n}"}]}`

The template I am using is unchanged from the last time the scale set was successfully deployed, however the scale set was deleted since the last successful deployment, and since then, deployment has failed.

I've tried deleting the whole scale set and redeploying, deleting only the two instances that fail and redeploying, deploying a single instance scale set and then scaling up one by one until hitting 4 instances, and nothing has worked.  The 3rd and 4th instances are always failing to implement the octopus dsc.

Any ideas?

Here is the template:

`{
  "$schema": "http://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "resources": [
    {
      "type": "Microsoft.Compute/virtualMachineScaleSets",
      "name": "staging-cmvm",
      "location": "northcentralus",
      "apiVersion": "2018-10-01",
      "tags": {
        "displayName": "VirtualMachines",
        "environment": "Staging"
      },
      "sku": {
        "name": "Standard_B2ms",
        "tier": "Standard",
        "capacity": 4
      },
      "properties": {
        "overprovision": false,
        "upgradePolicy": {
          "mode": "Automatic"
        },
        "virtualMachineProfile": {
          "storageProfile": {
            "osDisk": {
              "caching": "ReadOnly",
              "createOption": "FromImage",
              "managedDisk": {
                "storageAccountType": "Standard_LRS"
              }
            },
            "imageReference": {
              "publisher": "MicrosoftSQLServer",
              "offer": "SQL2016SP1-WS2016",
              "sku": "SQLDEV",
              "version": "13.2.190709"
            }
          },
          "osProfile": {
            "computerNamePrefix": "VM",
            "adminUsername": "<username>",
            "adminPassword": "<password>"
          },
          "networkProfile": {
            "networkInterfaceConfigurations": [
              {
                "name": "staging-cmvm-nic",
                "properties": {
                  "primary": true,
                  "ipConfigurations": [
                    {
                      "name": "staging-cmvm-ipconfig",
                      "properties": {
                        "subnet": {
                          "id": "[concat('/subscriptions/', subscription().subscriptionId,'/resourceGroups/', resourceGroup().name, '/providers/Microsoft.Network/virtualNetworks/', 'staging-vnet', '/subnets/', 'staging-subnet')]"
                        }
                      }
                    }
                  ]
                }
              }
            ]
          },
          "extensionProfile": {
            "extensions": [
              {
                "name": "SqlIaasExtension",
                "properties": {
                  "publisher": "Microsoft.SqlServer.Management",
                  "type": "SqlIaasAgent",
                  "typeHandlerVersion": "1.2",
                  "autoUpgradeMinorVersion": true,
                  "settings": {
                    "AutoPatchingSettings": {
                      "PatchCategory": "WindowsMandatoryUpdates",
                      "Enable": true,
                      "DayOfWeek": "Sunday",
                      "MaintenanceWindowStartingHour": "2",
                      "MaintenanceWindowDuration": "60"
                    }
                  }
                }
              },
              {
                "name": "dscExtension",
                "properties": {
                  "publisher": "Microsoft.Powershell",
                  "type": "DSC",
                  "typeHandlerVersion": "2.20",
                  "autoUpgradeMinorVersion": true,
                  "forceUpdateTag": "2",
                  "settings": {
                    "configuration": {
                      "url": "https://<URL>.blob.core.windows.net/scripts/OctopusTentacle.v3.zip",
                      "script": "OctopusTentacle.ps1",
                      "function": "OctopusTentacle"
                    },
                    "configurationArguments": {
                      "Name": "Staging",
                      "ApiKey": "<API Key>",
                      "OctopusServerUrl": "<URL>",
                      "Environments": "Staging",
                      "Roles": "<Role name>",
                      "ServerPort": <Port>
                    }
                  },
                  "protectedSettings": null
                }
              }
            ]
          }
        }
      }
    }
  ]
}`

**Comment by matt-richardson** [comment]
Hi @Andrew-Archon - sorry for the delay in getting back to you. Did you manage to resolve this?

If you didn't, can you check the logs under c:\octopus on the instances that are failing?
You can also use `Get-DscConfigurationStatus` on the box to get a bit more information about whats going on, or check the event log to see what errors are happening: `Get-WinEvent -LogName "Microsoft-Windows-Dsc/Operational"`

Check out https://docs.microsoft.com/en-us/powershell/scripting/dsc/troubleshooting/troubleshooting?view=powershell-6 for more details about how to diagnose errors.

**Comment by matt-richardson** [comment]
Closing due to no response. Please feel free to re-open if you’re still facing issues.
