### ISSUE TITLE
cTentacleAgent does not detect drift very well

### ISSUE THREAD

**Issue by trondhindenes** [OctopusDeploy/OctopusDSC#24]
If Get-TargetResource finds the Tentacle service to be present, it assumes that the tentacle is installed, which it may not be (as part of a reinstall etc). This ,coupled with the fact that uninstalling the tentacle doesn't seem to properly remove its own windows service, causes the dsc resource to incorrectly assume that the tentacle is already installed, when it very well may not be.

**Comment by matt-richardson** [comment]
Can you explain further what you mean here? I've just spent some time setting up some automated tests for this, and from what I can tell, it uninstalls correctly?

How could you get into a situation where the service is present, but the Tentacle is not installed? If the Tentacle was not installed, then the executable wouldn't be there, and therefore the service wouldn't run?

Regarding the tentacle not removing the windows service, it appears to for me?

```
Checking if Tentacle is installed
Tentacle present: True
Checking for Windows Service: OctopusDeploy Tentacle
Windows service: Running
Ensure: Present vs. Absent = False
 in 0.0160 seconds.

Checking if Tentacle is installed
Tentacle present: True
Checking for Windows Service: OctopusDeploy Tentacle
Windows service: Running
Configuring Tentacle...
Stopping OctopusDeploy Tentacle
Beginning Tentacle deregistration
Tentacle commands complete
Octopus Deploy: Tentacle version 3.5.1 (3.5.1+Branch.master.Sha.4feefbec21f18bc1b1908b5721dd03570fec86a6)
Deleting machine 'VAGRANT-2012-R2' from the Octopus server...
Machine deregistered successfully
Deleting service OctopusDeploy Tentacle...
[SC] DeleteService SUCCESS
Uninstalling Tentacle...
Tentacle MSI installer returned exit code 0
Finished
 in 3.7350 seconds.
```
 
If you're able to provide a failing test case, that would be awesome.

**Comment by trondhindenes** [comment]
Granted, we're on a older Octo version (3.3.10), but I've seen several occations that the service exists while the app was uninstalled. I think I figured that could happen if the service wasn't stopped prior to uninstalling. In either case, I think it would be preferable if dsc threw an error instead of just assuming that it is already installed whenever it finds the service to be present.

Lots of apps have this problem, and it's usually due to the msi uninstaller not properly cleaning up. If the uninstaller doesn't tell windows to remove the service, then it simply doesn't. 

I don't know what the support window for Octopus is (again, we're on a old version), but I'd be happy to retest the scenario on our environment and report back in more details.

**Comment by matt-richardson** [comment]
Hmm. Sounds odd.

Looking at the code, it checks to see if the msi is installed, and also if the service exists. If the msi is not installed, but the service is, it assumes its in a good state.

I'll have to have a ponder about it. I'm intending on making it work in a lot more situations, so I'll keep this in mind as I work on it.

If you can retest and see if you can reproduce the scenario, that would be good. Especially if we could understand how its uninstalled but the service exists.

**Comment by trondhindenes** [comment]
will do. I'm won't be able to see why it ends up in that state, but I can at least try and describe steps to repro. 

` If the msi is not installed, but the service is, it assumes its in a good state.`
This is the very logic I strongly disagree with.

**Comment by matt-richardson** [comment]
> This is the very logic I strongly disagree with, as it's not a positive result.

Agreed - its not great. I was just describing the code :)

**Comment by kamnel** [comment]
I have run into a similar situation when using Azure automation. My DSC configuration uses OctopusDSC module to install/configure a VM. In this particular instance the tentacle is installed correctly, but the tentacle failed to register with server (due to some issues that I am yet to figure out). I expected the next run of DSC should pickup that the tentacle is not-compliant and maybe attempt to apply the configuration again. However since the tentacle service is installed and Octopus.DSC.installstate is present DSC believes that everything is good.

**Comment by matt-richardson** [comment]
Hi @kamnel, can you raise a separate issue for this please? I think you're running into the limited drift detection rather than the issue @trondhindenes mentioned.

**Comment by trondhindenes** [comment]
I'm closing this since I completely forgot to follow up and there's a new version of the resource out. Providing feedback in new issues instead.
