### ISSUE TITLE
Resource always assumes public ip

### ISSUE THREAD

**Issue by trondhindenes** [OctopusDeploy/OctopusDSC#25]
The Set-TargetResource always assumes the octopus server should talk to the tentacle using the tentacle's public ip. In my experience, this is wrong 80% of the time. This setting needs to be configurable.

**Comment by hansmelin** [comment]
I agree! I have the same problem. All our deploy is done internally.

**Comment by matt-richardson** [comment]
Hi @trondhindenes - thanks for getting in touch.

I've just pushed a change that allows you to set a property `PublicHostNameConfiguration` to `PublicIp`, `FQDN`, `ComputerName` or `Custom`. If `Custom`, you can set another property `CustomPublicHostName` to the value you want.

Hope this helps!

**Comment by trondhindenes** [comment]
nice, awesome!
