### ISSUE TITLE
Current Pull Requests addressing Tentacle Url (Public IP)

### ISSUE THREAD

**Issue by hansmelin** [OctopusDeploy/OctopusDSC#26]
I can see that all open pull requests address the same issue. That the Tentacle Url is registered with the public ip address. I have suggestion for a solution that could solve the scenarios.

1. Introduce a new enum called TentacleUrlMode that will be used when resolving the URL. It could have following values:
   a. PublicIp - the same implementation as today
   b. FQDN - "$((Get-WmiObject win32_computersystem).DNSHostName).$((Get-WmiObject win32_computersystem).Domain)" - see http://stackoverflow.com/a/12268993
   c. ComputerName - $env:COMPUTERNAME
   d. CustomUrl
2. If CustomUrl is set as TentacleUrlMode you could provide this in a new property

**Comment by matt-richardson** [comment]
Thanks for getting in touch, @hansmelin. I was thinking something along the same lines. Hadn't quite put in as much thinking as you had as yet, but this is very useful to get the ball rolling.

**Comment by matt-richardson** [comment]
Hi @hansmelin - I've just pushed a change that implements this pretty much as you've suggested. Thanks for your input!

**Comment by hansmelin** [comment]
This is great news! I'm glad you are continuing the work on this project. I'm on a vacation right now. But I will test this new implementation as soon as I get back to work!
