### ISSUE TITLE
Change Tenanted Deployments mode

### ISSUE THREAD

**Issue by jeandoBet** [OctopusDeploy/OctopusDSC#275]
Hi,

Is there anyway to change the "Tenanted Deployments" mode on an agent? 

It is set by default to "Include only in tenanted deployments" when we add some tenanttags. 

But we would need to set it to "Include in both tenanted and untenanted deployments" for some of our agents

Any help would be really appreciated. Thank you

**Comment by matt-richardson** [comment]
You can do this via the `TenantedDeploymentParticipation` property - see https://github.com/OctopusDeploy/OctopusDSC/blob/master/README-cTentacleAgent.md.
