### ISSUE TITLE
cTentacleAgent with custom installation fails to find Tentacle.exe in previous install location

### ISSUE THREAD

**Issue by timothy-mcroy-cengage** [OctopusDeploy/OctopusDSC#276]
Situation: A server that already has the tentacle software installed becomes configured by cTentacleAgent.

Error: 
```
The term 'C:\Program Files\Octopus Deploy\Tentacle\Tentacle.exe' is not recognized as the name of a cmdlet, function,
script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is
correct and try again.
    + CategoryInfo          : ObjectNotFound: (C:\Program File...le\Tentacle.exe:) [], CimException
    + FullyQualifiedErrorId : CommandNotFoundException
    + PSComputerName        : SERVERNAME
```
However, you can also run the following on the host
```
PS C:\> (Get-ItemProperty -path "HKLM:\Software\Octopus\Tentacle" -ErrorAction SilentlyContinue).InstallLocation
D:\Program Files\Octopus Deploy\Tentacle\
```
My thoughts here: 
[The following function only checks the default install location ](https://github.com/OctopusDeploy/OctopusDSC/blob/24b448e6ac964ed938475add494a145c0473ac42/OctopusDSC/OctopusDSCHelpers.ps1#L196-L198)
Despite [this registry value ](https://github.com/OctopusDeploy/OctopusDSC/blob/24b448e6ac964ed938475add494a145c0473ac42/OctopusDSC/DSCResources/cTentacleAgent/cTentacleAgent.psm1#L274) storing the installation location anyway, but that location is never used other than to determine that the tentacle is installed.

**Comment by timothy-mcroy-cengage** [comment]
Light bump on this, since we're nearing 30 days

**Comment by poshpaws** [comment]
Also impacted by this issue , we have a mix of air gapped and internet allowed environments  
installing in C: is forbidden by company Policy so must use an alternative location with this and the tentacle  pre installed into the image
using this module results in it downloading the software thats already installed or just failing outright on the airgap env''s
please allow an override path or path detection
