### ISSUE TITLE
PSScriptAnalyzer issues

### ISSUE THREAD

**Issue by matt-richardson** [OctopusDeploy/OctopusDSC#30]
Hi OctopusDeploy, 

Thank you for contributing to the PowerShell Gallery. We have analyzed your item, OctopusDSC 2.0.26 and found it contains the following issues:

```
PSAvoidUsingUserNameAndPassWordParams
cOctopusServer.psm1, line 24
Function 'Get-TargetResource' has both Username and Password parameters. Either set the type 
of the Password parameter to SecureString or replace the Username and Password parameters
with a Credential parameter of type PSCredential. If using a Credential parameter in PowerShell
4.0 or earlier, please define a credential transformation attribute after the PSCredential type 
attribute.
```

```
PSAvoidUsingUserNameAndPassWordParams
cOctopusServer.psm1, line 232
Function 'Set-TargetResource' has both Username and Password parameters. Either set the type 
of the Password parameter to SecureString or replace the Username and Password parameters 
with a Credential parameter of type PSCredential. If using a Credential parameter in PowerShell 
4.0 or earlier, please define a credential transformation attribute after the PSCredential type 
attribute.
```

```
PSAvoidUsingUserNameAndPassWordParams
cOctopusServer.psm1, line 635
Function 'Install-OctopusDeploy' has both Username and Password parameters. Either set the 
type of the Password parameter to SecureString or replace the Username and Password 
parameters with a Credential parameter of type PSCredential. If using a Credential parameter in 
PowerShell 4.0 or earlier, please define a credential transformation attribute after the 
PSCredential type attribute.
```

```
PSAvoidUsingUserNameAndPassWordParams
cOctopusServer.psm1, line 819
Function 'Test-TargetResource' has both Username and Password parameters. Either set the type 
of the Password parameter to SecureString or replace the Username and Password parameters 
with a Credential parameter of type PSCredential. If using a Credential parameter in PowerShell 
4.0 or earlier, please define a credential transformation attribute after the PSCredential type 
attribute.
```

```
PSAvoidUsingConvertToSecureStringWithPlainText
cOctopusServer.psm1, line 759
File 'cOctopusServer.psm1' uses ConvertTo-SecureString with plaintext. This will expose secure 
information. Encrypted standard strings should be used instead.
```
These errors were generated by PowerShell Script Analyzer, which can be found at http://www.powershellgallery.com/packages/PSScriptAnalyzer/.

Please resolve the issues and then republish your item to the gallery.

Your feedback about PowerShell Script Analyzer rules or the scan itself is welcome. If you feel that the rules applied in your item's scan results are too restrictive or can result in false hits, please file an issue at https://github.com/powershell/psscriptanalyzer/issues. Alternatively, you can respond to this thread and let us know.

If you would like to unlist your item until the issue is resolved, please follow these steps:

1. Open http://www.powershellgallery.com, and sign in with your account credentials.
2. Click your account name in the upper right of the page.
3. Click Manage My Items.
4. Next to the item you want to unlist, click the Unlist icon.

If you would like us to delete the original item version, respond and let us know. Otherwise, your item can remain unlisted.

**Comment by stopthatastronaut** [comment]
v3.0.1 now passes PSScriptAnalyzer testing for the above mentioned rules. There is one remaining excepted rule which we believe isn't relevant to DSC Resources, `PSUseShouldProcessForStateChangingFunctions`

So, I'mma close off this Issue
