### ISSUE TITLE
Roles to be dynamically set, at client runtime

### ISSUE THREAD

**Issue by bronandrews** [OctopusDeploy/OctopusDSC#33]
Hey - not sure if this has been addressed and not sure how to request this properly.
Apologies if this is in completely wrong section!

But I need to be able to set the Octopus roles at runtime - i.e not a MOF creation, which currently seems to be the case.
Ideally, I have a seperate Script Resource that sets up the hashtable of roles I want, based on the client server the DSC Configuration is running on.
When it gets to the cTentacleAgent section, I'd like the "Roles = " part to dynamically read the hashtable variable from the Script Resource - is this possible?
Alternatively, I made the Script Resource write the Roles to a file and cTentacleAgent read from the file, but again it was looking to resolve the file content at MOF creation time, not at runtime, which is no good for me, as the Roles will only get decided on the client.
What can I do here?
Many thanks!

**Comment by bronandrews** [comment]
I see there is a new RolesFilePath property...I could try to use that to pick up file content on the client ?
But what OctopusDSC module version is this in? The only module downloading for me is 2.0.26, which does not have this new property.

**Comment by matt-richardson** [comment]
Hi @bronandrews. @drryu had a similar request but [found a workaround](https://github.com/OctopusDeploy/OctopusDSC/pull/29#issuecomment-268833345) in that they could use an environment variable for this. You could have a script resource that sets the environment variable, and then the cTentacleAgent resource could read that.

Let me know how you go with that.

**Comment by drryu** [comment]
Hi @matt-richardson @bronandrews, this is still an issue.

Doesn't look like DSC allows variables to be set at run-time (http://stackoverflow.com/questions/29640108/can-i-have-dynamic-variables-in-dsc-file-resource), even with environment variables. 

The environment variables are in-place replaced when the mof is generated (server) and not on the client where it is run.

The best workaround I have found is to be write a file to client machine and then have the resource read from the file when installing the agent.

I have created a pull request with this feature. Please review.

**Comment by bronandrews** [comment]
@drryu @matt-richardson 
Thanks for confirming, 
I didn't think Environment variables would work as the Roles property seems to resolve when the mof is generated, no matter what you do!

Is your workaround using the new RolesFilePath property? - I saw your Pull Request on that.
Will that definitely resolve at runtime, as opposed to mof creation time?

I tried something like that with the Roles property
i.e. 
Script Resource had:
    $RolesToUse > C:\RolesToUse.txt

and then the cTentacleAgent Resource had:
    Roles = Get-Content C:\RolesToUse.txt

But it still looked for the the file locally on the server while creating the mof file, and never read the client one at runtime.

If this new RolesFilePath property works I'd like to try it.
Is that available in a release yet?
The latest module version that downloads is 2.0.26 which does not have it.
Many thanks.

**Comment by bronandrews** [comment]
Hi - any update on my queries?
Is the workaround to use RolesFilePath property? and how what version can I get which incorporates that?

Many thanks!

**Comment by matt-richardson** [comment]
Hi @bronandrews

That [PR](https://github.com/OctopusDeploy/OctopusDSC/pull/34) has not been merged as I'm not convinced its the best approach. I think its probably better to follow the approach outlined in [how to separate configuration and environment data](https://msdn.microsoft.com/en-us/powershell/dsc/configdata).

Let me know how that works for you.

**Comment by arcotek-ltd** [comment]
Hi @matt-richardson,

Could you explain how one can use the information in ["how to separate configuration and environment data"](https://docs.microsoft.com/en-us/powershell/dsc/configdata) to get over the massive shortcoming of DSC where it is not possible to read variables at **run-time**?

(apart from a script resource, but then what do we do with it? How do you use a script resource's return in the rest of the configuration?)

It breaks the idea of "treating servers as cattle and not pets" as one has to know the name of the node before compiling the DSC as in building the AllNodes array of NodeName hashtables in $ConfigurationData.

It also means that each node needs its own configuration, so if one wants to make a change to the configuration, one has to change every node's configuration. (I'm sure it could be scripted, but it's not the point).

It is possible to have one 'monolithic' configuration that can be applied to 'localhost' but the theory breaks when we need a variable that is only available after compilation.

Think Azure template:
1.  Compile DSC for roles A, B & C 
2.  Create VM for roles A (Database)
3.  Apply DSC to VM. The configuration has an `if ($role -eq A){apply these DSC resources}` 
4.  Create VM for role B & C (App + web server)
5.  Apply DSC to VM, but I need to tell B & C what the hostname of A is, at runtime.

I hope the above is a good enough reason why you proposed solution won't work and why you need to reopen this issue.

Thanks
