### ISSUE TITLE
cTentacleAgent CustomPublicHostName is not a member

### ISSUE THREAD

**Issue by JarrodJ83** [OctopusDeploy/OctopusDSC#38]
Is there a good place to see what properties are in which versions of this resource? I'm using what I believe is the latest version (2.0.57) and it does not contain CustomPublicHostName. 

If I understand this property correctly I can use it to avoid disconnected Azure VMs with dynamic IPs that get re-assigned upon restart. This is the problem I'm currently trying to fix with this resource.

**Comment by matt-richardson** [comment]
`2.0.57` is the latest version, correct. There's no easy way to figure out whats in a given release at the moment, unfortunately.

Just looking at the code, the `CustomPublicHostName` all appears to be there, but its missing from the `mof` file.

I'll take a look soon.

**Comment by matt-richardson** [comment]
This should be fixed in version `2.0.63`.

Can you give it a test and let me know how it goes?

**Comment by JarrodJ83** [comment]
Works like a charm. Thanks for the quick turnaround!
