### ISSUE TITLE
Add the ability to override the public host name used for registration

### ISSUE THREAD

**Issue by PaulStovell** [OctopusDeploy/OctopusDSC#4]

**Comment by matt-richardson** [comment]
Hi all - thanks for getting in touch.

I've just pushed a change that allows you to set a property `PublicHostNameConfiguration` to `PublicIp`, `FQDN`, `ComputerName` or `Custom`. If `Custom`, you can set another property `CustomPublicHostName` to the value you want.

Hope this helps!
