### ISSUE TITLE
Specify tentacle service account

### ISSUE THREAD

**Issue by hansmelin** [OctopusDeploy/OctopusDSC#40]
It would be great to have the ability to specify which account should run the tentacle service. Because sometimes you need elevated permissions to access a share etc.

Compare with the `[PSCredential] SQLSvcAccount` for e.g. xSQLServerSetup https://github.com/PowerShell/xSQLServer#xsqlserversetup

**Comment by matt-richardson** [comment]
Hi @hansmelin 

Thanks for the suggestion. At the moment, we are unlikely to tackle this in the near future, however we are very happy to accept PRs for this kind of thing.

As a side note, we've been putting some thought into how we handle usernames/passwords in our DSC.  We are going against the PSScriptAnalyzer guidelines with the way we do it with the server, but given how painful it is to use `PSCredential` objects (with the [encryption setup](https://blogs.infosupport.com/safely-using-pscredentials-in-a-powershell-dsc-configuration/) you need to do), we're not sure if following the guidelines is the best thing to do.

Are you already using the encryption setup to pass `PSCredential`'s around? If people are already doing it, then us following the best practice wont be so painful.

**Comment by hansmelin** [comment]
I totally agree that it is painful.

I'm still in the testing phase and I'm creating the credentials with clear text password for now. But I tremble at the thought of setting up certificates etc. 

So I welcome alternative ways of handling credentials.

**Comment by zentron** [comment]
Thanks again for your comment @hansmelin . As @matt-richardson mentioned we have no immediate plans to rectify this in the near term. Please let us know however if you run into any other issues in the meantime.

**Comment by matt-richardson** [comment]
I had meant to add a note to this discussion a while back.

We discussed this internally, and came to the conclusion that the best approach would be to add the `PSCredential` as originally suggested. It is a pain, but its a pain that is common across a lot of DSC resources. This, combined with the fact that it is considered best practice means its probably the best approach.

**Comment by elovelan** [comment]
@matt-richardson, just a heads up, we at @BeazleyLabs have just started working on this have experience with the certificate setup (though using it in testing will require some research into best practices).

Just want to confirm we're not overlapping any internal work over at Octopus Deploy.

If not, any thoughts on parameter names? 
`$tentacleUsername` & `$tenacleUserPassword`
`$runAsUsername` & `$runAsPassword`
are two options I'm considering

cc @belogix

**Comment by matt-richardson** [comment]
Great to hear, @elovelan. Happy to assist where I can. We are not looking at this at the moment, so feel free to charge ahead.

I think we'll need to use a `PSCredential` object rather than having username and password fields. I'd suggest `TentacleServiceAccount` for the variable name.

I'll re-open this issue now that you guys are looking to implement.

**Comment by elovelan** [comment]
Yes, that makes sense, I intended to use a `PSCredential` to store the password but have a separate username like the [built-in `User` resource](https://msdn.microsoft.com/en-us/powershell/dsc/userresource), but I realize now that it makes more sense to have a single `PSCredential` like the [`Service` resource](https://msdn.microsoft.com/en-us/powershell/dsc/serviceresource)

**Comment by stopthatastronaut** [comment]
Tentacle service account can now be set using a PSCredential object, as of v3.0.1

Examples can be found under /Tests/Scenarios - best practice of course is to [encrypt those credentials](http://duffney.io/Encrypting-DSC-Credentials) but obviously we don't do that in the test scenarios.

Cheers!
