### ISSUE TITLE
Tenants and Tenant Tags functionality

### ISSUE THREAD

**Issue by mb290** [OctopusDeploy/OctopusDSC#41]
The ability to specify a tenant and tenant tag functionality was missing in the Tentacle Agent DSC files. I needed it pretty urgently so wrote the code this weekend and was wanting to do a pull request. I've configured the fields as optional so if you don't specify anything the switches don't get passed into the tentacle execution allow it to be backwards compatible. 

I won't get a chance to spin vagrant up for a week or so but wanted to know if you'd be interested in the pull request sooner? I've already tested it and using in a deployment with both tags defined and undefined. 

The code is in [https://github.com/mb290/OctopusDSC/tree/master/OctopusDSC/DSCResources/cTentacleAgent](https://github.com/mb290/OctopusDSC/tree/master/OctopusDSC/DSCResources/cTentacleAgent) already if you want to take a look

**Comment by alfhenrik** [comment]
Hey @mb290 we'd happily accept a PR for this functionality, feel free to send the PR through whenever suits you. 😄 

Cheers,
Henrik

**Comment by matt-richardson** [comment]
Fixed by #42.
