### ISSUE TITLE
cTentacleAgent $TentacleHomeDirectory doesnt take whitespace chars

### ISSUE THREAD

**Issue by dhjensen** [OctopusDeploy/OctopusDSC#43]
If you use 'c:\give me white\spaces please' the MSI install part till stall forever.

Also in that context there seem to be no error handling of msi installs that fail to start because of bad parameters.

**Comment by zentron** [comment]
Thanks for the find @dhjensen . I have added this into a GitHub issue to track in our central repository [here](https://github.com/OctopusDeploy/Issues/issues/3226) so that it can be triaged and actioned. In the meantime feel free to request a PR if you think you can provide a quite fix.
Cheers
