### ISSUE TITLE
cTentacleAgent install fails, unable to find Octopus.DSC.installstate

### ISSUE THREAD

**Issue by twerthi** [OctopusDeploy/OctopusDSC#50]
From the logs, it looks like there may be a hardcoded location to find the file after the .MSI is done installing.  The installation completes successfully and it successfully connects to the Octopus server.

VERBOSE: Perform operation 'Invoke CimMethod' with following parameters, ''methodName' =
SendConfigurationApply,'className' = MSFT_DSCLocalConfigurationManager,'namespaceName' =
root/Microsoft/Windows/DesiredStateConfiguration'.
VERBOSE: An LCM method call arrived from computer DEL-Z122090 with user sid
S-1-5-21-1844237615-1844823847-839522115-74788.
VERBOSE: [DEL-Z122090]: LCM:  [ Start  Set      ]
VERBOSE: [DEL-Z122090]: LCM:  [ Start  Resource ]  [[cTentacleAgent]OctopusTentacle]
VERBOSE: [DEL-Z122090]: LCM:  [ Start  Test     ]  [[cTentacleAgent]OctopusTentacle]
VERBOSE: [DEL-Z122090]:                            [[cTentacleAgent]OctopusTentacle] Checking if Tentacle is installed
VERBOSE: [DEL-Z122090]:                            [[cTentacleAgent]OctopusTentacle] Tentacle present: False
VERBOSE: [DEL-Z122090]:                            [[cTentacleAgent]OctopusTentacle] Checking for Windows Service:
OctopusDeploy Tentacle
VERBOSE: [DEL-Z122090]:                            [[cTentacleAgent]OctopusTentacle] Windows service: Not installed
VERBOSE: [DEL-Z122090]:                            [[cTentacleAgent]OctopusTentacle] Ensure: Absent vs. Present = False
VERBOSE: [DEL-Z122090]: LCM:  [ End    Test     ]  [[cTentacleAgent]OctopusTentacle]  in 0.6560 seconds.
VERBOSE: [DEL-Z122090]: LCM:  [ Start  Set      ]  [[cTentacleAgent]OctopusTentacle]
VERBOSE: [DEL-Z122090]:                            [[cTentacleAgent]OctopusTentacle] Checking if Tentacle is installed
VERBOSE: [DEL-Z122090]:                            [[cTentacleAgent]OctopusTentacle] Tentacle present: False
VERBOSE: [DEL-Z122090]:                            [[cTentacleAgent]OctopusTentacle] Checking for Windows Service:
OctopusDeploy Tentacle
VERBOSE: [DEL-Z122090]:                            [[cTentacleAgent]OctopusTentacle] Windows service: Not installed
VERBOSE: [DEL-Z122090]:                            [[cTentacleAgent]OctopusTentacle] Configuring Tentacle...
VERBOSE: [DEL-Z122090]:                            [[cTentacleAgent]OctopusTentacle] Installing Tentacle...
VERBOSE: [DEL-Z122090]:                            [[cTentacleAgent]OctopusTentacle] Beginning Tentacle installation
VERBOSE: [DEL-Z122090]:                            [[cTentacleAgent]OctopusTentacle] Downloading Octopus Tentacle MSI
from http://octopusdeploy.com/downloads/latest/OctopusTentacle64 to e:\Octopus\Tentacle.msi
VERBOSE: [DEL-Z122090]:                            [[cTentacleAgent]OctopusTentacle] Downloading
http://octopusdeploy.com/downloads/latest/OctopusTentacle64 to e:\Octopus\Tentacle.msi
VERBOSE: [DEL-Z122090]:                            [[cTentacleAgent]OctopusTentacle] Installing MSI...
VERBOSE: [DEL-Z122090]:                            [[cTentacleAgent]OctopusTentacle] Tentacle MSI installer returned
exit code 0
**Could not find a part of the path 'C:\Octopus\Octopus.DSC.installstate'.
    + CategoryInfo          : ObjectNotFound: (C:\Octopus\Octopus.DSC.installstate:) [], CimException
    + FullyQualifiedErrorId : GetContentWriterDirectoryNotFoundError,Microsoft.PowerShell.Commands.SetContentCommand
    + PSComputerName        : localhost**

VERBOSE: [DEL-Z122090]:                            [[cTentacleAgent]OctopusTentacle] Open port 10933 on Windows
Firewall
VERBOSE: [DEL-Z122090]:                            [[cTentacleAgent]OctopusTentacle] Ok.
VERBOSE: [DEL-Z122090]:                            [[cTentacleAgent]OctopusTentacle] Configuring and registering
Tentacle
VERBOSE: [DEL-Z122090]:                            [[cTentacleAgent]OctopusTentacle] Tentacle configuration set as
e:\Octopus\Tentacle\Tentacle.config
VERBOSE: [DEL-Z122090]:                            [[cTentacleAgent]OctopusTentacle] Octopus Deploy: Tentacle version
3.12.6 (3.12.6+Branch.master.Sha.5fd77c79b36c7f0307dd3d34b855749a23564bce) instance Tentacle
VERBOSE: [DEL-Z122090]:                            [[cTentacleAgent]OctopusTentacle] Environment Information:
VERBOSE: [DEL-Z122090]:                            [[cTentacleAgent]OctopusTentacle]   OperatingSystem: Microsoft
Windows NT 6.2.9200.0
VERBOSE: [DEL-Z122090]:                            [[cTentacleAgent]OctopusTentacle]   OsBitVersion: x64
VERBOSE: [DEL-Z122090]:                            [[cTentacleAgent]OctopusTentacle]   Is64BitProcess: True
VERBOSE: [DEL-Z122090]:                            [[cTentacleAgent]OctopusTentacle]   CurrentUser: NT AUTHORITY\SYSTEM
VERBOSE: [DEL-Z122090]:                            [[cTentacleAgent]OctopusTentacle]   MachineName: DEL-Z122090
VERBOSE: [DEL-Z122090]:                            [[cTentacleAgent]OctopusTentacle]   ProcessorCount: 4
VERBOSE: [DEL-Z122090]:                            [[cTentacleAgent]OctopusTentacle]   CurrentDirectory: C:\Program
Files\Octopus Deploy\Tentacle
VERBOSE: [DEL-Z122090]:                            [[cTentacleAgent]OctopusTentacle]   TempDirectory: C:\Windows\TEMP\
VERBOSE: [DEL-Z122090]:                            [[cTentacleAgent]OctopusTentacle]   HostProcessName: Tentacle
VERBOSE: [DEL-Z122090]:                            [[cTentacleAgent]OctopusTentacle] Saving instance: Tentacle
VERBOSE: [DEL-Z122090]:                            [[cTentacleAgent]OctopusTentacle] Octopus Deploy: Tentacle version
3.12.6 (3.12.6+Branch.master.Sha.5fd77c79b36c7f0307dd3d34b855749a23564bce) instance Tentacle
VERBOSE: [DEL-Z122090]:                            [[cTentacleAgent]OctopusTentacle] Environment Information:
VERBOSE: [DEL-Z122090]:                            [[cTentacleAgent]OctopusTentacle]   OperatingSystem: Microsoft
Windows NT 6.2.9200.0
VERBOSE: [DEL-Z122090]:                            [[cTentacleAgent]OctopusTentacle]   OsBitVersion: x64
VERBOSE: [DEL-Z122090]:                            [[cTentacleAgent]OctopusTentacle]   Is64BitProcess: True
VERBOSE: [DEL-Z122090]:                            [[cTentacleAgent]OctopusTentacle]   CurrentUser: NT AUTHORITY\SYSTEM
VERBOSE: [DEL-Z122090]:                            [[cTentacleAgent]OctopusTentacle]   MachineName: DEL-Z122090
VERBOSE: [DEL-Z122090]:                            [[cTentacleAgent]OctopusTentacle]   ProcessorCount: 4
VERBOSE: [DEL-Z122090]:                            [[cTentacleAgent]OctopusTentacle]   CurrentDirectory: C:\Program
Files\Octopus Deploy\Tentacle
VERBOSE: [DEL-Z122090]:                            [[cTentacleAgent]OctopusTentacle]   TempDirectory: C:\Windows\TEMP\
VERBOSE: [DEL-Z122090]:                            [[cTentacleAgent]OctopusTentacle]   HostProcessName: Tentacle
VERBOSE: [DEL-Z122090]:                            [[cTentacleAgent]OctopusTentacle] Home directory set to: e:\Octopus
VERBOSE: [DEL-Z122090]:                            [[cTentacleAgent]OctopusTentacle] Octopus Deploy: Tentacle version
3.12.6 (3.12.6+Branch.master.Sha.5fd77c79b36c7f0307dd3d34b855749a23564bce) instance Tentacle
VERBOSE: [DEL-Z122090]:                            [[cTentacleAgent]OctopusTentacle] Environment Information:
VERBOSE: [DEL-Z122090]:                            [[cTentacleAgent]OctopusTentacle]   OperatingSystem: Microsoft
Windows NT 6.2.9200.0
VERBOSE: [DEL-Z122090]:                            [[cTentacleAgent]OctopusTentacle]   OsBitVersion: x64
VERBOSE: [DEL-Z122090]:                            [[cTentacleAgent]OctopusTentacle]   Is64BitProcess: True
VERBOSE: [DEL-Z122090]:                            [[cTentacleAgent]OctopusTentacle]   CurrentUser: NT AUTHORITY\SYSTEM
VERBOSE: [DEL-Z122090]:                            [[cTentacleAgent]OctopusTentacle]   MachineName: DEL-Z122090
VERBOSE: [DEL-Z122090]:                            [[cTentacleAgent]OctopusTentacle]   ProcessorCount: 4
VERBOSE: [DEL-Z122090]:                            [[cTentacleAgent]OctopusTentacle]   CurrentDirectory: C:\Program
Files\Octopus Deploy\Tentacle
VERBOSE: [DEL-Z122090]:                            [[cTentacleAgent]OctopusTentacle]   TempDirectory: C:\Windows\TEMP\
VERBOSE: [DEL-Z122090]:                            [[cTentacleAgent]OctopusTentacle]   HostProcessName: Tentacle
VERBOSE: [DEL-Z122090]:                            [[cTentacleAgent]OctopusTentacle] Application directory set to:
e:\Temp
VERBOSE: [DEL-Z122090]:                            [[cTentacleAgent]OctopusTentacle] Octopus Deploy: Tentacle version
3.12.6 (3.12.6+Branch.master.Sha.5fd77c79b36c7f0307dd3d34b855749a23564bce) instance Tentacle
VERBOSE: [DEL-Z122090]:                            [[cTentacleAgent]OctopusTentacle] Environment Information:
VERBOSE: [DEL-Z122090]:                            [[cTentacleAgent]OctopusTentacle]   OperatingSystem: Microsoft
Windows NT 6.2.9200.0
VERBOSE: [DEL-Z122090]:                            [[cTentacleAgent]OctopusTentacle]   OsBitVersion: x64
VERBOSE: [DEL-Z122090]:                            [[cTentacleAgent]OctopusTentacle]   Is64BitProcess: True
VERBOSE: [DEL-Z122090]:                            [[cTentacleAgent]OctopusTentacle]   CurrentUser: NT AUTHORITY\SYSTEM
VERBOSE: [DEL-Z122090]:                            [[cTentacleAgent]OctopusTentacle]   MachineName: DEL-Z122090
VERBOSE: [DEL-Z122090]:                            [[cTentacleAgent]OctopusTentacle]   ProcessorCount: 4
VERBOSE: [DEL-Z122090]:                            [[cTentacleAgent]OctopusTentacle]   CurrentDirectory: C:\Program
Files\Octopus Deploy\Tentacle
VERBOSE: [DEL-Z122090]:                            [[cTentacleAgent]OctopusTentacle]   TempDirectory: C:\Windows\TEMP\
VERBOSE: [DEL-Z122090]:                            [[cTentacleAgent]OctopusTentacle]   HostProcessName: Tentacle
VERBOSE: [DEL-Z122090]:                            [[cTentacleAgent]OctopusTentacle] A new certificate has been
generated and installed. Thumbprint:
VERBOSE: [DEL-Z122090]:                            [[cTentacleAgent]OctopusTentacle]
590847334942A318B54C02ECB965C091450393F3
VERBOSE: [DEL-Z122090]:                            [[cTentacleAgent]OctopusTentacle] Octopus Deploy: Tentacle version
3.12.6 (3.12.6+Branch.master.Sha.5fd77c79b36c7f0307dd3d34b855749a23564bce) instance Tentacle
VERBOSE: [DEL-Z122090]:                            [[cTentacleAgent]OctopusTentacle] Environment Information:
VERBOSE: [DEL-Z122090]:                            [[cTentacleAgent]OctopusTentacle]   OperatingSystem: Microsoft
Windows NT 6.2.9200.0
VERBOSE: [DEL-Z122090]:                            [[cTentacleAgent]OctopusTentacle]   OsBitVersion: x64
VERBOSE: [DEL-Z122090]:                            [[cTentacleAgent]OctopusTentacle]   Is64BitProcess: True
VERBOSE: [DEL-Z122090]:                            [[cTentacleAgent]OctopusTentacle]   CurrentUser: NT AUTHORITY\SYSTEM
VERBOSE: [DEL-Z122090]:                            [[cTentacleAgent]OctopusTentacle]   MachineName: DEL-Z122090
VERBOSE: [DEL-Z122090]:                            [[cTentacleAgent]OctopusTentacle]   ProcessorCount: 4
VERBOSE: [DEL-Z122090]:                            [[cTentacleAgent]OctopusTentacle]   CurrentDirectory: C:\Program
Files\Octopus Deploy\Tentacle
VERBOSE: [DEL-Z122090]:                            [[cTentacleAgent]OctopusTentacle]   TempDirectory: C:\Windows\TEMP\
VERBOSE: [DEL-Z122090]:                            [[cTentacleAgent]OctopusTentacle]   HostProcessName: Tentacle
VERBOSE: [DEL-Z122090]:                            [[cTentacleAgent]OctopusTentacle] Services listen port: 10933
VERBOSE: [DEL-Z122090]:                            [[cTentacleAgent]OctopusTentacle] Getting public IP address
VERBOSE: [DEL-Z122090]:                            [[cTentacleAgent]OctopusTentacle] GET https://api.ipify.org/ with
0-byte payload
VERBOSE: [DEL-Z122090]:                            [[cTentacleAgent]OctopusTentacle] received 12-byte response of
content type text/plain
VERBOSE: [DEL-Z122090]:                            [[cTentacleAgent]OctopusTentacle] Public host name: 198.238.3.44
VERBOSE: [DEL-Z122090]:                            [[cTentacleAgent]OctopusTentacle] Octopus Deploy: Tentacle version
3.12.6 (3.12.6+Branch.master.Sha.5fd77c79b36c7f0307dd3d34b855749a23564bce) instance Tentacle
VERBOSE: [DEL-Z122090]:                            [[cTentacleAgent]OctopusTentacle] Environment Information:
VERBOSE: [DEL-Z122090]:                            [[cTentacleAgent]OctopusTentacle]   OperatingSystem: Microsoft
Windows NT 6.2.9200.0
VERBOSE: [DEL-Z122090]:                            [[cTentacleAgent]OctopusTentacle]   OsBitVersion: x64
VERBOSE: [DEL-Z122090]:                            [[cTentacleAgent]OctopusTentacle]   Is64BitProcess: True
VERBOSE: [DEL-Z122090]:                            [[cTentacleAgent]OctopusTentacle]   CurrentUser: NT AUTHORITY\SYSTEM
VERBOSE: [DEL-Z122090]:                            [[cTentacleAgent]OctopusTentacle]   MachineName: DEL-Z122090
VERBOSE: [DEL-Z122090]:                            [[cTentacleAgent]OctopusTentacle]   ProcessorCount: 4
VERBOSE: [DEL-Z122090]:                            [[cTentacleAgent]OctopusTentacle]   CurrentDirectory: C:\Program
Files\Octopus Deploy\Tentacle
VERBOSE: [DEL-Z122090]:                            [[cTentacleAgent]OctopusTentacle]   TempDirectory: C:\Windows\TEMP\
VERBOSE: [DEL-Z122090]:                            [[cTentacleAgent]OctopusTentacle]   HostProcessName: Tentacle
VERBOSE: [DEL-Z122090]:                            [[cTentacleAgent]OctopusTentacle] Service installed
VERBOSE: [DEL-Z122090]:                            [[cTentacleAgent]OctopusTentacle] Registering with arguments:
register-with --instance Tentacle --server http://MyOctoServer --name MachineName --apiKey
API-KEY --force --console --comms-style TentaclePassive --publicHostName 198.238.3.44
--environment ShawnTest --role Database
VERBOSE: [DEL-Z122090]:                            [[cTentacleAgent]OctopusTentacle] Octopus Deploy: Tentacle version
3.12.6 (3.12.6+Branch.master.Sha.5fd77c79b36c7f0307dd3d34b855749a23564bce) instance Tentacle
VERBOSE: [DEL-Z122090]:                            [[cTentacleAgent]OctopusTentacle] Environment Information:
VERBOSE: [DEL-Z122090]:                            [[cTentacleAgent]OctopusTentacle]   OperatingSystem: Microsoft
Windows NT 6.2.9200.0
VERBOSE: [DEL-Z122090]:                            [[cTentacleAgent]OctopusTentacle]   OsBitVersion: x64
VERBOSE: [DEL-Z122090]:                            [[cTentacleAgent]OctopusTentacle]   Is64BitProcess: True
VERBOSE: [DEL-Z122090]:                            [[cTentacleAgent]OctopusTentacle]   CurrentUser: NT AUTHORITY\SYSTEM
VERBOSE: [DEL-Z122090]:                            [[cTentacleAgent]OctopusTentacle]   MachineName: DEL-Z122090
VERBOSE: [DEL-Z122090]:                            [[cTentacleAgent]OctopusTentacle]   ProcessorCount: 4
VERBOSE: [DEL-Z122090]:                            [[cTentacleAgent]OctopusTentacle]   CurrentDirectory: C:\Program
Files\Octopus Deploy\Tentacle
VERBOSE: [DEL-Z122090]:                            [[cTentacleAgent]OctopusTentacle]   TempDirectory: C:\Windows\TEMP\
VERBOSE: [DEL-Z122090]:                            [[cTentacleAgent]OctopusTentacle]   HostProcessName: Tentacle
VERBOSE: [DEL-Z122090]:                            [[cTentacleAgent]OctopusTentacle] Registering the tentacle with the
server at http://deploy.del.wa.gov/
VERBOSE: [DEL-Z122090]:                            [[cTentacleAgent]OctopusTentacle] Machine registered successfully
VERBOSE: [DEL-Z122090]:                            [[cTentacleAgent]OctopusTentacle] Tentacle commands complete
VERBOSE: [DEL-Z122090]:                            [[cTentacleAgent]OctopusTentacle] Tentacle installed!
VERBOSE: [DEL-Z122090]:                            [[cTentacleAgent]OctopusTentacle] Starting OctopusDeploy Tentacle
VERBOSE: [DEL-Z122090]:                            [[cTentacleAgent]OctopusTentacle] Finished
VERBOSE: [DEL-Z122090]: LCM:  [ End    Set      ]  [[cTentacleAgent]OctopusTentacle]  in 14.6930 seconds.
The PowerShell DSC resource '[cTentacleAgent]OctopusTentacle' with SourceInfo
'E:\Development-Active\InstallTentacle.ps1::24::3::cTentacleAgent' threw one or more non-terminating errors while
running the Set-TargetResource functionality. These errors are logged to the ETW channel called
Microsoft-Windows-DSC/Operational. Refer to this channel for more details.
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : NonTerminatingErrorFromProvider
    + PSComputerName        : localhost

VERBOSE: [DEL-Z122090]: LCM:  [ End    Set      ]
The SendConfigurationApply function did not succeed.
    + CategoryInfo          : NotSpecified: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : MI RESULT 1
    + PSComputerName        : localhost

VERBOSE: Operation 'Invoke CimMethod' complete.
VERBOSE: Time taken for configuration job to complete is 16.019 seconds

Here is my configuration

Param($OctopusAPIKey,
	$OctopusRoles,
	$OctopusEnvironments,
	$OctopusServerUrl,
    $TempPath
)

# configure Ocotpus Deploy
Configuration OctopusSetup
{
	# define parameters
	Param($OctopusAPIKey,
		$OctopusRoles,
		$OctopusEnvironments,
		$OctopusServerUrl
	)

	# import necessary resources
	Import-DscResource -Module OctopusDSC

	# create localhost configuration node
	Node "localhost"
	{
		cTentacleAgent OctopusTentacle
		{
			Name = "Tentacle"
            DisplayName = $env:COMPUTERNAME
            Ensure = "Present"
			State = "Started"
			ApiKey = $OctopusAPIKey
			OctopusServerUrl = $OctopusServerUrl
			Environments = $OctopusEnvironments
			Roles = $OctopusRoles
            CommunicationMode = "Listen"
            DefaultApplicationDirectory = "e:\Temp"
            TentacleHomeDirectory = "e:\Octopus"
		}
	}
}

# run configureation 
OctopusSetup -OctopusAPIKey $OctopusAPIKey -OctopusRoles $OctopusRoles -OctopusEnvironments $OctopusEnvironments -OctopusServerUrl $OctopusServerUrl -OutputPath $TempPath

# start the configuration
Start-DscConfiguration -Path $TempPath -Verbose -Wait

**Comment by twerthi** [comment]
Confirmed this occurs only when TentacleHomeDirectory is set.

**Comment by twerthi** [comment]
The workaround is to include a File node in your configuration

        # ensure the necessary folders exist
        File OctopusInstallWorkaround
        {
            Type = "Directory"
            DestinationPath = "c:\Octopus"
            Ensure = "Present"
        }

**Comment by matt-richardson** [comment]
Thanks for the detailed bug report, and even more for the tracking down the root cause and providing a workaround.

I've just pushed a fix that should resolve it - it should be live in about 20 mins or so after it goes through the test pipeline. It should be released as `2.0.104`.

Can you give it a go and let me know if it resolves the issue for you? Unfortunately its not that simple to test as part of the pipeline we've got setup.

**Comment by twerthi** [comment]
Confirmed, it is how working as desired :)  Thanks for the quick turn around!
