### ISSUE TITLE
Specify Installation Directory

### ISSUE THREAD

**Issue by msnelling** [OctopusDeploy/OctopusDSC#51]
It would be useful to be able to specify the installation/home directory. For example we're using Amazon EC2, Terraform and Ansible to deploy and provision our Octopus server. We would like to have the packages repository on an EBS volume that can be remounted when we teardown/recreate a new instance of the server.

**Comment by matt-richardson** [comment]
@msnelling, @rohmcd, @fodoj:

To make sure I understand your request, is it just the home directory you want to change? ie:
```
.\Octopus.Server.exe configure --home <homepath>
```

You _dont_ mean:
* config file path (eg `c:\octopus\octopus.config`)
* application installation directory (eg `c:\program files\octopus deploy\octopus`)
* any of the paths you can customise using the `path` command (the package repository directory, the artifacts directory or the tasklogs directory (all of these end up under the `home` directory if not set))

The PR above will allow you to customise the home directory, but none of the others. At the moment, its hard to check what the current value of the other paths are (until I make a change in the server).

**Comment by msnelling** [comment]
@matt-richardson Yes it's the`--home` parameter I want to be able to set.

**Comment by matt-richardson** [comment]
This is now available in version `2.0.176`.
