### ISSUE TITLE
Tentacle watchdog support

### ISSUE THREAD

**Issue by HamsterExAstris** [OctopusDeploy/OctopusDSC#53]
Octopus Deploy v3.7.17 added a feature to create a scheduled task to make sure the Tentacle was running (the "watchdog"): https://github.com/OctopusDeploy/Issues/issues/3067

It doesn't look like this is currently supported. Would you accept a PR to add support for that to New-Tentacle()?

**Comment by matt-richardson** [comment]
That would be much appreciated.

That said, I wonder if it would make sense for it to be a different resource?

**Comment by matt-richardson** [comment]
Thinking more about this, I think there should be a `cOctopusServerWatchdog` resource and a `cTentacleWatchdog` resource. 

The challenge is going to be determining the current state, as there's no easy way of seeing this, without a big chunk of code to check the scheduled task. Hmm.

I'll take a look and see if we can add a command `Tentacle.exe watchdog --status --format json` or similar to output the status of the watchdog.

**Comment by matt-richardson** [comment]
Implemented by #64.

Available in version 2.0.143. Requires Octopus `3.17.0` (or above) and Tentacle `3.15.8` (or above).
