### ISSUE TITLE
Getting error at the end of the run

### ISSUE THREAD

**Issue by Fodoj** [OctopusDeploy/OctopusDSC#62]
DSC seems to have configured Octopus, but at the very end of the run it throws this error at me:

```
VERBOSE: [IP-AC165207]:                            [[cOctopusServer]OctopusServer] Windows service: Running
VERBOSE: [IP-AC165207]:                            [[cOctopusServer]OctopusServer] Importing server configuration file from 'C:\Octopus\Octo
pusServer.config'
VERBOSE: [IP-AC165207]: LCM:  [ End    Test     ]  [[cOctopusServer]OctopusServer]  in 3.2470 seconds.
PowerShell DSC resource cOctopusServer  failed to execute Test-TargetResource functionality with error message: Invalid object passed in, 
':' or '}' expected. (1): { 
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : localhost
 
The SendConfigurationApply function did not succeed.
    + CategoryInfo          : NotSpecified: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : MI RESULT 1
    + PSComputerName        : localhost
 
VERBOSE: Operation 'Invoke CimMethod' complete.
VERBOSE: Time taken for configuration job to complete is 3.377 seconds
```

I'm using powershell 4 and windows server 2012 r2

How can I fix it?

**Comment by stopthatastronaut** [comment]
Hi Dave,

Looks like it's failing at the point where we run Octopus commandline with the `show-configuration` switch. In current versions of Octopus, this should return valid JSON, but it looks like it's not in your case.

So, the obvious first question: what version of Octopus do you have installed? Could be we're incorrectly detecting the version, or we could be running into another error entirely.

Also, could you try running the following command on your server and see what comes back?

`Octopus.Server.exe show-configuration --format=json-hierarchical --noconsolelogging --console --instance <your instance name here>`

That's the command that's failing under the covers so running it on its own should give us some insight.

Thanks,
Jason
Octopus Deploy

**Comment by Fodoj** [comment]
I am using octopus 3.11.9 - would that work?

**Comment by stopthatastronaut** [comment]
The show-configuration command dropped in Octopus 3.5, so 3.11 should be OK. I think maybe running the command to check the output might help at this point.

thanks
Jason

**Comment by Fodoj** [comment]
Command above returns correct JSON

**Comment by matt-richardson** [comment]
@Fodoj - can you check the [event log](https://blogs.msdn.microsoft.com/powershell/2014/01/03/using-event-logs-to-diagnose-errors-in-desired-state-configuration/) and see if there's anything of interest in there?

Can you also share the configuration you're passing in, and the result of the `show-configuration` command (make sure to redact anything sensitive).

**Comment by matt-richardson** [comment]
Closing due to lack of response. If you are still having an issue, please let us know.
