### ISSUE TITLE
cOctopusServer & cTentacleAgent shouldn't re-download an installer if a matching installer is on-disk

### ISSUE THREAD

**Issue by stopthatastronaut** [OctopusDeploy/OctopusDSC#71]
Fairly easy change to make in `Function Request-File`. We provide checksums as HTTP headers `x-amz-meta-md5` and `x-amz-meta-sha256`, we should check these against the target file on disk (if it exists)

**Comment by stopthatastronaut** [comment]
Probably quite easy to add a pester test for this, too.

**Comment by adrian-andersson** [comment]
Any updates on this?

**Comment by adhodgson1** [comment]
I just checked and it looks like this is already implemented in the function.  Not sure if this issue needs to be closed.

**Comment by stopthatastronaut** [comment]
Yep, this issue didn't get closed as it should have. Closing now.
